import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers, AuthProvider } from "./providers";
import { fonts } from "./fonts";
import "../app/globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={fonts.rubik.variable}>
            <body className={inter.className}>
              <Providers><AuthProvider>{children}</AuthProvider></Providers>
            </body>
        </html>
    );
}
